config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :meetings do
    collection do
      get "/send-mails", to: "send_mails#index", as: "send_mails"
      post "/send-mails", to: "meetings#send_mails", as: "send_mail"
    end
  end
  devise_for :users, controllers: {
    confirmations: "confirmations"
  }
  resources :rooms
  get "users/show", to: "users#show"
  root "rooms#index"
end

app/models/meeting.rb
# frozen_string_literal: true

# Meeting Model
class Meeting < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :subject, presence: true, length: { minimum: 5 }

  validates_presence_of :date, :start_time, :end_time

  validates_format_of :meeting_url, with: %r{\A(https?://)?([\da-z.-]+)\.([a-z.]{2,6})([/\w.-]*)*/?\Z}i

  validate :meeting_start_date

  validate :schedule

  validate :start_and_end_time

  def time_format(time)
    Time.parse(time.to_s).strftime("%H:%M %p")
  end

  before_save do
    self.subject = subject.titleize
  end

  def start_and_end_time
    if Date.parse(date.to_s) < Date.parse(Time.now.to_s) && (Time.parse(start_time.to_s) < Time.now)
      errors.add(:start_time, "can't be in the past!")
    end

    errors.add(:start_time, "cant' start before end time!") if end_time < start_time
    errors.add(:end_time, "start time and end time can't be same") if start_time == end_time
  end

  def meeting_start_date
    errors.add(:date, "Can't be in the past!") if Date.parse(date.to_s) < Date.parse(Time.now.to_s)
  end

  def schedule
    data = Meeting.select(:start_time, :end_time, :id).where(date: date).where.not(id: id).where(room_id: room_id)

    data.each do |meeting|
      errors.add(:start_time, "Meeting is scheduled before another meeting is over!") if start_time < meeting.end_time
      if meeting.start_time.hour == start_time.hour && (start_time.min <= meeting.end_time.min)
        errors.add(:start_time, "Meeting has already been schedule on this time!!")
      end
    end
  end
end

app/controllers/meetings_controller.rb
# frozen_string_literal: true

# Meeting Controller
class MeetingsController < DashboardsController
  before_action :authenticate_user!
  before_action :set_meeting, only: %i[show edit update destroy]

  # GET /meetings or
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  def show; end

  # GET /meetings/new
  def new
    authorize! :create, Meeting
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
    authorize! :update, Meeting
  end

  # POST /meetings
  def create
    authorize! :create, Meeting
    @meeting = Meeting.new(meeting_params)

    if @meeting.save
      redirect_to meeting_url(@meeting), notice: "Meeting was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /meetings/1
  def update
    authorize! :update, Meeting
    if @meeting.update(meeting_params)
      redirect_to meeting_url(@meeting), notice: "Meeting was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /meetings/1
  def destroy
    authorize! :destroy, Meeting
    @meeting.destroy

    redirect_to meetings_url, notice: "Meeting was successfully destroyed."
  end

  def send_mails
    authorize! :update, Meeting
    @meeting = Meeting.find_by_id(params[:meeting])
    if @meeting
      @meeting.members.each do |member|
        MeetingMailer.with(meeting: @meeting, member: member).send_mail.deliver_now
      end

      redirect_to send_mail_meetings_path, notice: "Mail is sent to all members."
    else
      redirect_to send_mail_meetings_path, alert: "Could not sent mails."
    end
  end

  private

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:subject, :meeting_url, :room_id, :date, :start_time, :end_time, :user_id,
                                    members: [])
  end
end

app/views/meetings/_form.html.erb
<section class="container meeting-form-container">
  <%= form_with(model: meeting) do |form| %>
    <% if meeting.errors.any? %>
      <div style="color: red">
        <ul>
          <% meeting.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :subject, class: "form-label" %>
      <%= form.text_field :subject, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :members, class: "form-check-label" %>
      <%# <% if meeting[:members].size > 0 %>
      <span class="badge bg-success position-relative selected-count-container">
        Selected 
        <span class="badge bg-danger" id="selected-count"><%= meeting[:members].size %> </span>
      </span>
      <%# <% end %>
      <% User.pluck(:email).each do |member| %>
        <div class="form-check">
          <input class="form-check-input member" id=<%= member%> 
            <%= meeting.members.include?(member)? "checked": "" %> 
            type="checkbox" name= "meeting[members][]" 
            value=<%= member%> 
            onclick="update_count()" 
          />
          <label class="form-check-label" for=<%= member %>><%= member%></label>
          </div>
        <% end %>
      </div>
      <div class="mb-3">
        <%= form.label :room_id, class: "form-label" %>
        <%= form.select :room_id, Room.pluck(:id).map { |room| ["Room-#{room}", room]}, {}, class: "form-select"  %>
      </div>
      <div class="mb-3">
        <%= form.label :date, class: "form-label" %>
        <%= form.date_field :date, class: "form-control", required: true %>
      </div>
      <div class="mb-3">
        <%= form.label :start_time, class: "form-label" %>
        <%= form.time_field :start_time, class: "form-control", required: true %>
      </div>
      <div class="mb-3">
        <%= form.label :end_time, class: "form-label" %>
        <%= form.time_field :end_time, class: "form-control", required: true %>
      </div>
      <div class="mb-3">
        <%= form.label :user_id, "Host By", class: "form-label" %>
        <%= form.select :user_id, User.pluck(:email, :id), {}, class: "form-select" %>
      </div>
      <div class="mb-3">
        <%= form.label :meeting_url, "Meeting URL", class: "form-label" %>
        <%= form.url_field :meeting_url, class: "form-control", required: true %>
      </div>
      <div class="mb-3 d-flex">
        <%= form.submit "Save", class: "flex-grow-1 btn btn-sm btn-primary" %>
      </div>
    <% end %>
  </section>
  <script>
    setVisibility(Number(document.querySelector("#selected-count").innerHTML));
  </script>

app/views/meetings/_meeting.html.erb
<section class="container mt-2">
  <div id="<%= dom_id meeting %>">
    <table class="table table-striped">
      <tr>
        <th>Subject:</th>
        <td><%= meeting.subject %></td>
      </tr>
      <tr>
        <th>Host by:</th>
        <td><%= meeting.user.username %> (<%= meeting.user.email %>)</td>
      </tr>
      <tr>
        <th><strong>Room no:</strong></th>
        <td><%= link_to "Room-#{meeting.room_id}", room_path(meeting.room) %></td>
      </tr>
      <tr>
        <th>Date:</th>
        <td><%= meeting.date %></td>
      </tr>
      <tr>
        <th>Start time:</th>
        <td><%= meeting.time_format(meeting.start_time) %></td>
      </tr>
      <tr>
        <th>End time:</th>
        <td><%= meeting.time_format(meeting.end_time) %></td>
      </tr>
      <tr>
        <th>Meeting Link:</th>
        <td><%= link_to meeting.meeting_url, meeting.meeting_url, target: "_blank" %></td>
      </tr>
      <tr>
        <th><strong>Members:</strong></th>
        <td>
          <% meeting.members.each do |member| %>
            <div><%= member %></div>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</section>

app/views/meetings/edit.html.erb
<h4 class="text-success">Update meeting details</h4>

<%= render "form", meeting: @meeting %>

<br>

<div>
  <%= link_to "Show this meeting", @meeting %> |
  <%= link_to "Back to meetings", meetings_path %>
</div>

app/views/meetings/index.html.erb
<section class="rooms-header d-flex align-items-center justify-content-between pt-3 mb-1">
  <h4 class="text-primary mb-0">Meetings</h4>
  <% if can? :read, @meetings %>
    <%= link_to "New Meeting", new_meeting_path, class: "btn btn-primary " %>
  <% end %>
</section>
<table class="table table-hover">
  <thead class="table-primary">
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Subject</th>
      <th scope="col">Created By</th>
      <th scope="col">Date</th>
      <th scope="col">Room</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @meetings.each_with_index do |meeting, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= meeting.subject %></td>
        <td><%= meeting.room.user.email %></td>
        <td><%= meeting.created_at.strftime("%d/%m/%Y %H:%M %p") %></td>
        <td><%= link_to "Room no-#{meeting.room_id}", room_path(meeting.room) %></td>
        <td>
          <div class="meeting-actions d-flex align-items-center justify-content-end">
            <%= link_to "View", meeting, class: "btn btn-sm btn-success" %> &nbsp;
            <% if can? :update, meeting %>
              <%= link_to "Edit", edit_meeting_path(meeting), class: "btn btn-primary btn-sm" %> &nbsp;
              <%= button_to "Remove", meeting, class: "btn btn-sm btn-danger", method: :delete %>
            <% end %>
            &nbsp;
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/meetings/new.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h4 class="text-primary">New meeting</h4>
  <%= link_to "Back to meetings", meetings_path, class: "btn btn-secondary btn-sm" %>
</div>
<%= render "form", meeting: @meeting %>

app/views/meetings/show.html.erb
<section class="container meeting-header" >
 <div class="d-flex justify-content-between align-items-center">
   <h4 class="text-success">
    Meeting Details:
  </h4>

  <div class="meeting-details-actions">
    <% if can? :update, @meeting %>
      <%= link_to "Edit this meeting", edit_meeting_path(@meeting), class: "btn btn-success btn-sm" %> &nbsp;
    <% end%>
    <%= link_to "Back to meetings", meetings_path, class: "btn btn-primary btn-sm" %>
  </div>
 </div>
</section>

<%= render @meeting %>

<% if can? :destroy, @meeting %>
  <div class="d-flex justify-content-end" >
    <%= button_to "Delete this meeting", @meeting, method: :delete, class: "btn btn-sm btn-danger" %>
  </div>
<% end %>