config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :meetings do
    collection do
      get "/send-mails", to: "send_mails#index", as: "send_mails"
      post "/send-mails", to: "meetings#send_mails", as: "send_mail"
    end
  end
  devise_for :users, controllers: {
    confirmations: "confirmations"
  }
  resources :rooms
  get "users/show", to: "users#show"
  root "rooms#index"
end

app/views/shared/_flash_alert.html.erb
<div id="message">
  <% if notice %>
  <div class="alert alert-success mt-3 alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>
  <% if alert %>
  <div class="alert alert-primary mt-3 alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Meeting Room Scheduler", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item ">
          <span class="nav-link active badge bg-primary"><%= current_user.role.titleize %></span>
        </li>
      </ul>
      <div class="d-flex align-items-center">
        <% if user_signed_in? %>
        <div class="nav_item_">
           <%= link_to "Profile", users_show_path, class: "nav-link text-muted" %>
        </div>
          <div class="nav-item_">
            <span class="nav-link text-white">WELCOME, <%= current_user.username.titleize %> !!</span>
          </div>
          <div class="nav-item_">
            <%= button_to 'SIGN OUT', destroy_user_session_path, method: :delete,  class:"btn btn-danger btn-sm" %>
          </div>
        <% else %>
          <div class="nav-item_">
            <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-sm btn-primary" %>
            <%= link_to 'Login', new_user_session_path, class: "ml-2 btn btn-sm btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>