config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :meetings do
    collection do
      get "/send-mails", to: "send_mails#index", as: "send_mails"
      post "/send-mails", to: "meetings#send_mails", as: "send_mail"
    end
  end
  devise_for :users, controllers: {
    confirmations: "confirmations"
  }
  resources :rooms
  get "users/show", to: "users#show"
  root "rooms#index"
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  belongs_to :user
  has_many :meetings, dependent: :destroy

  validates :description, presence: true, length: { minimum: 5, maximum: 300 }
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

# Rooms Controller
class RoomsController < DashboardsController
  before_action :authenticate_user!
  before_action :set_room, only: %i[show edit update destroy]

  # GET /rooms
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  def show
    @meetings = Meeting.where(room: @room)
  end

  # GET /rooms/new
  def new
    @room = Room.new
    authorize! :create, Room
  end

  # GET /rooms/1/edit
  def edit
    authorize! :update, Room
  end

  # POST /rooms
  def create
    authorize! :create, Room
    @room = Room.new(room_params)
    @room.user = current_user

    if @room.save
      redirect_to rooms_path, notice: "Room was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /rooms/1
  def update
    if @room.update(room_params)
      redirect_to room_url(@room), notice: "Room was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /rooms/1
  def destroy
    authorize! :destroy, Room
    @room.destroy

    redirect_to rooms_url, notice: "Room was successfully destroyed."
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:description)
  end
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h6><%= pluralize(room.errors.count, "error") %></h6>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <div class="mt-3 d-flex justify-content-end">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rooms/_meetings.html.erb
<section class="rooms-header d-flex align-items-center justify-content-between pt-3 mb-1">
  <h5 class="text-primary mb-0">Assigned meetings on this room</h5>
  <% if can? :read, @meetings %>
    <%= link_to "Insert new", new_meeting_path, class: "btn btn-sm btn-primary " %>
  <% end %>
</section>
<table class="table table-hover">
  <thead>
    <tr style="font-size: .9rem">
      <th scope="col">SN</th>
      <th scope="col">Subject</th>
      <th scope="col">Created By</th>
      <th scope="col">Date</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody style="font-size: .9rem">
    <% meetings.each_with_index do |meeting, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= meeting.subject %></td>
        <td><%= meeting.room.user.email %></td>
        <td><%= meeting.created_at %></td>
        <td>
          <div class="meeting-actions d-flex align-items-center justify-content-end">
            <%= link_to "View", meeting, class: "btn btn-sm btn-success", style: "padding: 5px; font-size:.7rem" %> &nbsp;
            <% if can? :update, meeting %>
              <%= link_to "Edit", edit_meeting_path(meeting), class: "btn btn-primary btn-sm", style: "padding: 5px; font-size:.7rem" %> &nbsp;
              <%= button_to "Remove", meeting, class: "btn btn-sm btn-danger", method: :delete, style: "padding: 5px; font-size:.7rem" %>
            <% end %>
            &nbsp;
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/_room.html.erb
<section class="container">
  <div id="<%= dom_id room %>">
    <p>
      <strong>Description:</strong>
      <%= room.description %>
    </p>

    <p>
      <strong>Room Created By:</strong>
      <%= room.user.email %>
    </p>

  </div>
</section>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<section class="rooms-header d-flex align-items-center justify-content-between pt-3 mb-1">
  <h4 class="text-primary mb-0">Rooms</h4>
  <% if can? :read, current_user %>
    <%= link_to "New room", new_room_path, class: "btn btn-primary " %>
  <% end %>
</section>
<table class="table table-hover">
  <thead class="table-primary">
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Description</th>
      <th scope="col">Created By</th>
      <th scope="col">Date</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each_with_index do |room, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= room.description %></td>
        <td><%= room.user.username.titleize %></td>
        <td><%= room.created_at.strftime("%d/%m/%Y %H:%M %p") %></td>
        <td>
          <div class="room-actions d-flex align-items-center justify-content-end">
            <%= link_to "View", room, class: "btn btn-sm btn-success" %> &nbsp;
            <% if can? :update, @room %>
              <%= link_to "Edit", edit_room_path(room), class: "btn btn-primary btn-sm" %> &nbsp;
              <%= button_to "Remove", room, class: "btn btn-sm btn-danger", method: :delete %>
              &nbsp;
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/new.html.erb
<h4>New room</h4>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path, class: "btn btn-secondary" %>
</div>

app/views/rooms/show.html.erb
<section class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h4 class="text-success">
      Room Details: 
    </h4>
    <div>
      <% if can? :update, @room %>
        <%= link_to "Edit", edit_room_path(@room), class: "btn btn-sm btn-primary" %>
      <% end %>
      <%= link_to "Back", :back, class: "btn btn-sm btn-secondary" %>
    </div>
  </div>
  <%= render @room %>
  <% if can? :destroy, @room %>
    <div>
      <%= button_to "Remove this room", @room, method: :delete, class: "btn btn-danger btn-sm" %>
    </div>
  <% end %>
</section>
<%= render "meetings", meetings: @meetings%>