config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :meetings do
    collection do
      get "/send-mails", to: "send_mails#index", as: "send_mails"
      post "/send-mails", to: "meetings#send_mails", as: "send_mail"
    end
  end
  devise_for :users, controllers: {
    confirmations: "confirmations"
  }
  resources :rooms
  get "users/show", to: "users#show"
  root "rooms#index"
end

app/views/layouts/_flash_alert.html.erb
<div class="container">
  <div id="message">
    <% if notice %>
    <div class="alert alert-success mt-3" role="alert">
      <%= notice %>
    </div>
    <% end %>
    <% if alert %>
    <div class="alert alert-danger mt-3" role="alert">
      <%= alert %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <title>Meeting Room Scheduler(MRS)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= favicon_link_tag asset_path('meeting-room-scheduler.ico') %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
  <%= render 'shared/flash_alert' %>
  <%= yield %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <title>Meeting Room Sheduler(MRS)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= favicon_link_tag asset_path('meeting-room-scheduler.ico') %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
  <%= render "shared/navbar" %>
  <div id="wrapper">
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li><%= link_to "Rooms", rooms_path, class: "nav-link active" %></li>
        <li> <%= link_to "Meetings", meetings_path, class: "nav-link active" %></li>
        <% if current_user.admin? %>
          <li><%= link_to "Send Mails", send_mails_meetings_path, class: "nav-link active" %></li>
        <% end %>
      </ul>
    </div>
    <section class="container">
      <%= render "shared/flash_alert" %>
      <section class="p-5">
        <%= yield %>
      </section>
    </section>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>